version: "3.7"

services:
  back:
    build: ./BACK
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
  front:
    build: ./FRONT
    ports:
      - 5173:5173
    extra_hosts:
      - "host.docker.internal:host-gateway"
